export const UTILITIES: Record<string, string> = {
	"bg-primary": "background-color:var(--colors-primary);",
	"bg-surface": "background-color:var(--colors-surface);",
	"bg-white": "background-color:var(--colors-white);",

	// Borders (colors, widths, sides, styles)
	"border": "border-width:1px;border-style:solid;border-color:var(--colors-text);",
	"border-0": "border-width:0;border-style:solid;",
	"border-2": "border-width:2px;border-style:solid;",
	"border-4": "border-width:4px;border-style:solid;",
	"border-8": "border-width:8px;border-style:solid;",
	"border-b": "border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:var(--colors-text);",
	"border-b-0": "border-bottom-width:0;",
	"border-b-2": "border-bottom-width:2px;",
	"border-b-4": "border-bottom-width:4px;",
	"border-b-primary": "border-bottom-color:var(--colors-primary);",
	"border-black": "border-color:var(--colors-black);",
	"border-dashed": "border-style:dashed;",
	"border-dotted": "border-style:dotted;",
	"border-l": "border-left-width:1px;border-left-style:solid;border-left-color:var(--colors-text);",
	"border-l-0": "border-left-width:0;",
	"border-l-2": "border-left-width:2px;",
	"border-l-4": "border-left-width:4px;",
	"border-l-primary": "border-left-color:var(--colors-primary);",
	"border-none": "border-style:none;",
	"border-primary": "border-color:var(--colors-primary);",
	"border-r": "border-right-width:1px;border-right-style:solid;border-right-color:var(--colors-text);",
	"border-r-0": "border-right-width:0;",
	"border-r-2": "border-right-width:2px;",
	"border-r-4": "border-right-width:4px;",
	"border-r-primary": "border-right-color:var(--colors-primary);",
	"border-solid": "border-style:solid;",
	"border-surface": "border-color:var(--colors-surface);",
	"border-t": "border-top-width:1px;border-top-style:solid;border-top-color:var(--colors-text);",
	"border-t-0": "border-top-width:0;",
	"border-t-2": "border-top-width:2px;",
	"border-t-4": "border-top-width:4px;",
	"border-t-primary": "border-top-color:var(--colors-primary);",
	"border-text": "border-color:var(--colors-text);",
	"border-white": "border-color:var(--colors-white);",

	"font-bold": "font-weight:bold;",

	// Margin
	"m-2": "margin:var(--spacing-2);",
	"m-3": "margin:var(--spacing-3);",
	"m-4": "margin:var(--spacing-4);",
	"mb-2": "margin-bottom:var(--spacing-2);",
	"ml-2": "margin-left:var(--spacing-2);",
	"mr-2": "margin-right:var(--spacing-2);",
	"mt-2": "margin-top:var(--spacing-2);",
	"mx-4": "margin-left:var(--spacing-4);margin-right:var(--spacing-4);",
	"my-2": "margin-top:var(--spacing-2);margin-bottom:var(--spacing-2);",
	"my-3": "margin-top:var(--spacing-3);margin-bottom:var(--spacing-3);",

	// Padding
	"p-2": "padding:var(--spacing-2);",
	"p-3": "padding:var(--spacing-3);",
	"p-4": "padding:var(--spacing-4);",
	"pb-2": "padding-bottom:var(--spacing-2);",
	"pl-2": "padding-left:var(--spacing-2);",
	"pr-2": "padding-right:var(--spacing-2);",
	"pt-2": "padding-top:var(--spacing-2);",
	"px-4": "padding-left:var(--spacing-4);padding-right:var(--spacing-4);",
	"py-2": "padding-top:var(--spacing-2);padding-bottom:var(--spacing-2);",
	"py-3": "padding-top:var(--spacing-3);padding-bottom:var(--spacing-3);",

	// Radius
	"rounded": "border-radius:var(--radius-md);",
	"rounded-md": "border-radius:var(--radius-lg);",

	// Shadow
	"shadow-2xl": "box-shadow:0 25px 50px rgba(0,0,0,0.1);",
	"shadow-lg": "box-shadow:0 10px 15px rgba(0,0,0,0.1);",
	"shadow-md": "box-shadow:0 4px 6px rgba(0,0,0,0.1);",
	"shadow-sm": "box-shadow:0 1px 3px rgba(0,0,0,0.1);",
	"shadow-xl": "box-shadow:0 20px 25px rgba(0,0,0,0.1);",

	// Typography
	"text-2xl": "font-size:24px;",
	"text-base": "font-size:16px;",
	"text-black": "color:var(--colors-black);",
	"text-center": "text-align:center;",
	"text-lg": "font-size:18px;",
	"text-primary": "color:var(--colors-primary);",
	"text-sm": "font-size:14px;",
	"text-white": "color:var(--colors-white);",
	"text-xl": "font-size:20px;"
}
