name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && github.ref_name && github.ref_protected == true
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Verify branch is main
        run: |
          DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
          if [ "$DEFAULT_BRANCH" != "main" ]; then echo "Default branch is not main"; exit 1; fi
          CURRENT_BRANCH=$(git branch -r --contains $GITHUB_SHA | sed -n 's#  origin/##p' | head -n1)
          if [ "$CURRENT_BRANCH" != "main" ]; then echo "Tag not on main"; exit 1; fi
      - name: Install
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Publish to npm
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish --access public
